#!/usr/bin/env bash
# shellcheck disable=SC2155 enable=require-variable-braces

set -Exeo pipefail
auth_header=()
if [ -n "${GITHUB_TOKEN}" ]; then
    auth_header=("-H" "Authorization: token ${GITHUB_TOKEN}")
fi

# set CWD to the root of filecoin-ffi
#
cd "$(dirname "${BASH_SOURCE[0]}")"

# tracks where the C++ sources are were we to build locally instead of
# downloading from GitHub Releases
#
prover_sources_dir="libs/cpp-fil-proofs"

main() {
    local __release_type=$(get_release_type)
    (>&2 echo "[install-filcrypto/main] building libfilcrypto from local sources (dir = ${prover_sources_dir})")

    # build libfilcrypto (and corresponding header and pkg-config)
    #
    build_from_source "filcrypto" "${prover_sources_dir}" "${__release_type}"

    # copy from CMake's build directory (target) to root of filecoin-ffi
    #
    find -L "${prover_sources_dir}/target/release" -type f -name filcrypto.h -exec cp -- "{}" . \;
    find -L "${prover_sources_dir}/target/release" -type f -name libfilcrypto.a -exec cp -- "{}" . \;
    find -L "${prover_sources_dir}" -type f -name filcrypto.pc -exec cp -- "{}" . \;

    check_installed_files

    (>&2 echo "[install-filcrypto/main] successfully built and installed libfilcrypto from source")
}

build_from_source() {
    local __library_name=$1
    local __cpp_sources_path=$2
    local __release_type=$3
    local __repo_sha1=$(git rev-parse HEAD)
    local __repo_sha1_truncated="${__repo_sha1:0:16}"
    local __target_feature=""

    (>&2 echo "building from source @ ${__repo_sha1_truncated}")

    if ! [ -x "$(command -v cmake)" ]; then
        (>&2 echo '[build_from_source] Error: CMake is not installed.')
        (>&2 echo '[build_from_source] install CMake (https://cmake.org) to resolve this problem.')
        exit 1
    fi

    cmake --version

    mkdir -p ${__cpp_sources_path}/build && cd ${__cpp_sources_path}/build

    cmake -DCMAKE_BUILD_TYPE=${__release_type} ..

    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        cmake --build . --target filecoin_proofs -- -j$nproc;
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        cmake --build . --target filecoin_proofs -- -j$(sysctl -n hw.logicalcpu);
    elif [[ "$OSTYPE" == "cygwin" ]]; then
       cmake --build . --target filecoin_proofs -- -j$nproc; 
    elif [[ "$OSTYPE" == "msys" ]]; then
        cmake --build . --target filecoin_proofs -- -j$nproc;
    elif [[ "$OSTYPE" == "freebsd"* ]]; then
        cmake --build . --target filecoin_proofs -- -j$(sysctl -n hw.logicalcpu);
    fi
}

check_installed_files() {
    if [[ ! -f "./filcrypto.h" ]]; then
        (>&2 echo "[check_installed_files] failed to install filcrypto.h")
        exit 1
    fi

    if [[ ! -f "./libfilcrypto.a" ]]; then
        (>&2 echo "[check_installed_files] failed to install libfilcrypto.a")
        exit 1
    fi

    if [[ ! -f "./filcrypto.pc" ]]; then
        (>&2 echo "[check_installed_files] failed to install filcrypto.pc")
        exit 1
    fi
}

main "$@"; exit
